name: markhor_movers
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  google_fonts: ^4.0.4
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  firebase_storage: ^11.4.0
  gap: ^3.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  firebase_core: ^2.21.0
  google_sign_in: ^6.1.5
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  location: ^5.0.3
  # google_maps_webservice: ^0.0.20-nullsafety.5
  dio: ^5.3.4
  geocoding: ^2.1.1
  flutter_polyline_points: ^1.0.0
  google_maps_place_picker_mb: ^3.0.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  provider: ^6.1.1
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

